### ISSUE TITLE
upper bound specification

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/robupy#1]
failure in test 3 for seed  23707
 failure in test 2 for seed  92908
 failure in test 2 for seed  91516
 failure in test 2 for seed  97542
 failure in test 2 for seed  43406

The failures for test 3 seeem to be related to the upper bound of the get_worst_case_probs bisection. Maybe I misunderstood its construction, also it says in the paper INITIAL bound ....

**Comment by MaxBlesch** [comment]
Outdated. I tried these seeds and everything works. I would close the issue if you have no objections!

**Comment by peisenha** [comment]
Thanks for checking!
