### ISSUE TITLE
Overflow handling

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/robupy#2]
if check_for_overflow:

        try:

            f = objfun(x, *args)

        except OverflowError:

            f = sys.float_info.max

from pyBOBYQA

**Comment by MaxBlesch** [comment]
Is this still an issue? Kind of no idea what's happening here? @peisenha

**Comment by peisenha** [comment]
I was struggelign with handling overflows at some point and saw this as it ensures that they do not propagate to upper levels.
